# Section A

This section contains 50 questions each of 5 marks. Each question in this section has 5 sub-questions which carry 1 mark each 

NOTE: If the question does not provide required array or list it is to the student to randomly generate one and work out for the solution.

## Q1
1. Import the numpy package under the name np
2. Print the numpy version and the configuration
3. Create a null vector of size 10
4. How to find the memory size of any array
5. Print an array of four Random Integers Between 1 and 100

In [9]:
#1
import numpy as np

In [10]:
#2
print(np.__version__)

1.16.4


In [11]:
#3
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Anudeep/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Anudeep/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Anudeep/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib',

In [121]:
#4
Z = np.zeros(10)
print(Z)
print("%d bytes" % (Z.size * Z.itemsize))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
80 bytes


In [16]:
#5
np.random.randint(low=1, high=100, size=4)

array([32, 99, 43, 85])

# Q2
1.	Create a null vector of size 10 but the fifth value which is 1
2.	Create a vector with values ranging from 10 to 49
3.	Reverse a vector (first element becomes last) 
4.	Create a 3x3 matrix with values ranging from 0 to 8 
5.	Find indices of non-zero elements from [1,2,0,0,4,0]

In [17]:
#1
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
#2
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#3
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [20]:
#4
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [21]:
#5
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# Q3
1.	Create a 3x3 identity matrix
2.	Create a 3x3x3 array with random values
3.	Create a 10x10 array with random values and find the minimum and maximum values
4.	Create a random vector of size 30 and find the mean value
5.	Create a 2d array with 1 on the border and 0 inside 

In [22]:
#1
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#2
Z = np.random.random((3,3,3))
print(Z)

[[[0.22685976 0.9873285  0.98724481]
  [0.52462201 0.01097092 0.58523914]
  [0.30704699 0.07888087 0.64188332]]

 [[0.71293143 0.62245086 0.47860589]
  [0.62050043 0.5330352  0.96308998]
  [0.38062565 0.52681113 0.09385442]]

 [[0.54779581 0.03046003 0.58735917]
  [0.18193876 0.52559785 0.00565192]
  [0.51871274 0.39245289 0.5209079 ]]]


In [24]:
#3
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0006660587686437847 0.9768166041140639


In [25]:
#4
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4861481851860925


In [26]:
#5
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Q4
###### 1. How to add a border (filled with 0's) around an existing array?
###### 2. What is the result of the following expression?

0 * np.nan |
np.nan == np.nan |
np.inf > np.nan |
np.nan - np.nan |
np.nan in set([np.nan]) |
0.3 == 3 * 0.1 |


###### 3.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
###### 4.Create a 8x8 matrix and fill it with a checkerboard pattern
###### 5.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [27]:
#1
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [28]:
#2
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [29]:
#3
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [30]:
#4
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [31]:
#5
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


# Q5

1. Create a checkerboard 8x8 matrix using the tile function
2. Normalize a 5x5 random matrix
3. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
4. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
5. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [32]:
#1
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [33]:
#2
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.73564822  0.23402425  1.65119342  1.33126299 -0.72700644]
 [ 0.67289747 -0.04218472  0.28036695 -1.00178766  1.41553101]
 [-1.42337628  0.6513035   0.13305909  1.24807197 -0.11902264]
 [-1.61310185 -0.9092063  -0.53151758  0.6105547   1.54390777]
 [-1.55351265 -1.03057788 -0.57144632  0.22914261 -1.21422361]]


In [34]:
#3
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [35]:
#4
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [36]:
#5
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# Q6

1. Consider an integer vector Z, Is Z**Z legal?
2. Consider an integer vector Z, Is 2 << Z >> 2  legal?
3. Consider an integer vector Z, Is Z <- Z legal?
4. How to round away from zero a float array ? 
5. How to find common values between two arrays?

In [125]:
#1
Z = np.dot(np.ones((5,3)), np.ones((3,2))) 
Z**Z
#Legal

array([[27., 27.],
       [27., 27.],
       [27., 27.],
       [27., 27.],
       [27., 27.]])

In [126]:
#2
2 << Z >> 2
#Illegal

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [127]:
#3
Z <- Z
#Legal

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [128]:
#4
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-1.  1.  3.  7.  8. -4. -4. -7. -6. -5.]


In [129]:
#5
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 4 7 9]


# Q7
1. How to ignore all numpy warnings (not recommended)?
2. Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)
3. Consider an integer vector Z, Is 1j*Z legal?
4. Consider an integer vector Z, Is Z/1/1 legal?
5. Consider an integer vector Z, Is Z<Z>Z legal?

In [42]:
#1
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [43]:
# Back to sanity
_ = np.seterr(**defaults)

In [44]:
# Equivalently with a context manager
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [45]:
#2
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Anudeep\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [130]:
#3
Z = np.dot(np.ones((5,3)), np.ones((3,2))) 
1j*Z
#legal

array([[0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j],
       [0.+3.j, 0.+3.j]])

In [131]:
#4
Z/1/1
#legal

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [132]:
#5
Z<Z>Z
#Illegal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Q8
1. Create a string called str1 and populate as "Great Learning". 
2. Print first character of the string 
3. Print last character of the string 
4. Print first three character of the string 
5. Print last three character of the string 

In [49]:
#1
str1 = "Great Learning"
#2
print (str1[0])        
#3
print (str1[-1])   
#4
print (str1[0:3])       
#5
print (str1[-3:])   

G
g
Gre
ing


# Q9

1. Create a string called str2 and populate as "Great Learning". 
2. Find length of the string str2
3. Find length of the string str2
4. Find index number for word Learning in the string str2 
5. Find nomber of white space within of the string str2

In [50]:
#1
str2 = "Great Learning"
#2
length = len(str2)
print(length)
#3
print (str2.count('G'))
#4
print (str2.index('Learning'))
#5
print (str2.count(' '))

14
1
6
1


# Q 10

1. Create a string "India is great" and print it.
2. Convert each character in Capital letter and print
3. Convert each character in small letter and print
4. Convert First character of each word as Capital rest in small letter and print
5. Convert only First character of whole string as Capital rest in small letter and print

In [51]:

#1
string = "India is great"
print (string)
#2
print (string.upper())
#3
print (string.lower())
#4
print (string.title())
#5
print (string.capitalize())


India is great
INDIA IS GREAT
india is great
India Is Great
India is great


# Q 11

1. Create a sting with your roll number and check if this sting is alphanumeric
2. Create a sting with your name and check if this sting has only alphabets no numbers
3. Create a two dimension numpy array  3x3 and display its content
4. Create a two dimension numpy array  3x3 and display its content
5. Access middle most (Cental element of the 2d array)

In [52]:
#1
GL_Rollno = "Bang_DSC_123"
print(GL_Rollno.isalnum()) 

#2
name = "Bharat"
print(name.isalpha())

#3
arr2dims = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr2dims

#4
arr2dims = np.array(([5,10,15],[20,25,30],[35,40,45]))
print(arr2dims)
#5
arr2dims[1][1]

False
True
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


25

# Q 12

1. Create a list with 5 single digit number (1 to 9)
2. Convert above into numpy array 
3. validate data of the Array by printing it
4. Print size of the array
5. Create a 4x4 zero matrix and print

In [53]:
#1
l1 = [1,2,3,4,5]

#2
Arr = np.array(l1)

#3
print(type(Arr))

#4
print(Arr.shape)

#5
zero = np.zeros((4,4))
print(zero)

<class 'numpy.ndarray'>
(5,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Q 13
string =" I love python "
1. Print the length of the string
2. Remove space from both the ends
3. Remove only left side whitespace
4. Remove only right side whitespace
5. Compare the lenghts of the string in each step

In [54]:
#1 string =" I love python "
print(string)
print(len(string))

#2
str3 = string.strip(' ')  ##removes space from both ends
print (str3)
print(len(str3))

#3
str4 = string.lstrip()    ##removes only left side whitespace
print (str4)
print(len(str4))

#4
str5 = string.rstrip()    #removes only side size whitespace
print (str5)
print(len(str5))
## add by validating last character such as str[-1]


 I love python 
15
I love python
13
I love python 
14
 I love python
14


# Q 14

battleDeaths = [482, 93, 392, 920, 813, 199, 374, 237, 244]

1. Create a function that updates all battle deaths by adding 100
2. Create a list that applies updated() to all elements of battleDeaths
3. Map the lambda function x() over battleDeaths
4. Remove first three entries of the list, battleDeaths and print the result
5. Append the list with the entry 145

In [55]:
#1
battleDeaths = [482, 93, 392, 920, 813, 199, 374, 237, 244]

def updated(x): return x + 100

In [56]:
#2
list(map(updated, battleDeaths))

[582, 193, 492, 1020, 913, 299, 474, 337, 344]

In [57]:
#3
list(map((lambda x: x + 100), battleDeaths))

[582, 193, 492, 1020, 913, 299, 474, 337, 344]

In [58]:
#4
newlist = battleDeaths[3:]
newlist

[920, 813, 199, 374, 237, 244]

In [59]:
#5
newlist.append(145)
newlist

[920, 813, 199, 374, 237, 244, 145]

# Q 15

1. Import the math module
2. Display the value of pi.
3. Absolute value
4. 32.09292 - Truncate (drop decimal digits)
5. 2.569 - Round by 2 digits


In [60]:
#1
import math

In [61]:
#2
math.pi

3.141592653589793

In [62]:
#3
abs(-20)

20

In [63]:
#4
math.trunc(32.09292)

32

In [64]:
#5
round(2.569, 2)

2.57

# SECTION B

This section contains 30 question each of 10 marks. Each question in this section may have 4 sub-questions which carry 2.5 marks each or 2 sub-questions each of 5 marks

NOTE: If the question does not provide required array or list it is to the student to randomly generate one and work out for the solution.

# Q 1
1. Extract the integer part of a random array using 5 different methods
2. Create a 5x5 matrix with row values ranging from 0 to 4
3. Consider a generator function that generates 10 integers and use it to build an array
4. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [65]:
#1
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[6. 7. 0. 1. 9. 7. 2. 9. 1. 0.]
[6. 7. 0. 1. 9. 7. 2. 9. 1. 0.]
[6. 7. 0. 1. 9. 7. 2. 9. 1. 0.]
[6 7 0 1 9 7 2 9 1 0]
[6. 7. 0. 1. 9. 7. 2. 9. 1. 0.]


In [66]:
#2
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [67]:
#3
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [68]:
#4
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# Q 2
1. Create a random vector of size 10 and sort it
2. How to sum a small array faster than np.sum?
3. Consider two random array A and B, check if they are equal
4. Make an array immutable (read-only)

In [69]:
#1
Z = np.random.random(10)
Z.sort()
print(Z)

[0.03628956 0.08649426 0.1156283  0.38222844 0.40667928 0.47338577
 0.74808082 0.90105422 0.96050519 0.96551908]


In [70]:
#2
Z = np.arange(10)
np.add.reduce(Z)

45

In [71]:
#3
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [72]:
#4
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

# Q 3

1. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
2. Create random vector of size 10 and replace the maximum value by 0
3. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
4. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [73]:
#1
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.59712228 0.25352955 0.6953355  0.83683428 0.59138586 0.62457268
 1.33998351 0.9163346  0.95351752 0.83850444]
[1.39159427 1.15660968 0.69862305 1.51179634 0.95608848 0.82111437
 0.80661696 1.41677078 0.13058794 1.26306858]


In [74]:
#2
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.83077684 0.28696231 0.62687695 0.3898976  0.65605987 0.32700401
 0.85385508 0.29013406 0.         0.23860837]


In [75]:
#3
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [76]:
#4
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


# Q 4
1. Print the minimum and maximum representable value for each numpy scalar type
2. How to print all the values of an array?
3. How to find the closest value (to a given scalar) in a vector?
4. Create a structured array representing a position (x,y) and a color (r,g,b)


In [77]:
#1
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [120]:
#2
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [79]:
#3
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

8


In [80]:
#4
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


# Q 5
1. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
2. How to convert a float (32 bits) array into an integer (32 bits) in place?
3. How to read the following file?
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

4. What is the equivalent of enumerate for numpy arrays?

In [81]:
#1
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.67490522 0.80027764 0.37535767 0.18153747 0.43971105
  0.7024046  0.79946599 0.23807085 0.93239006]
 [0.67490522 0.         0.76223602 0.33456513 0.50942482 0.24098502
  0.72794368 0.16690289 0.76914416 0.30062412]
 [0.80027764 0.76223602 0.         0.59402349 0.7969035  0.74794803
  0.10218587 0.91990343 0.64608821 0.7460805 ]
 [0.37535767 0.33456513 0.59402349 0.         0.25754257 0.17140783
  0.52245647 0.48911634 0.43484713 0.56024011]
 [0.18153747 0.50942482 0.7969035  0.25754257 0.         0.26899274
  0.70894336 0.62322139 0.37343022 0.78458236]
 [0.43971105 0.24098502 0.74794803 0.17140783 0.26899274 0.
  0.68437945 0.36122679 0.5666142  0.52680531]
 [0.7024046  0.72794368 0.10218587 0.52245647 0.70894336 0.68437945
  0.         0.89097439 0.54392584 0.75249915]
 [0.79946599 0.16690289 0.91990343 0.48911634 0.62322139 0.36122679
  0.89097439 0.         0.91893196 0.32661484]
 [0.23807085 0.76914416 0.64608821 0.43484713 0.37343022 0.5666142
  0.54392584 0.918931

In [82]:
#2
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[67 45 41 57 67 95 62 46 47 91]


In [83]:
#3
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [84]:
#4
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# Q 6
1. Generate a generic 2D Gaussian-like array (★★☆)
2. How to randomly place p elements in a 2D array? (★★☆)
3. Subtract the mean of each row of a matrix (★★☆)
4. How to sort an array by the nth column? (★★☆)

In [85]:
#1
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [86]:
#2
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [87]:
#3
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.32150273  0.02861855  0.53331109  0.11306039  0.42420172 -0.0647609
  -0.26678172 -0.11916356 -0.11227327 -0.21470957]
 [-0.06872136  0.21957601 -0.19036391  0.00641054  0.08981446 -0.09566456
   0.23770255  0.31400389 -0.50516239 -0.00759522]
 [-0.32580609  0.08489205  0.13841371 -0.16971876  0.20167321  0.02889372
   0.07778262  0.08326217 -0.31443231  0.19503969]
 [-0.30263291  0.49773401 -0.12020825 -0.16269239 -0.39629691  0.46826737
   0.43896703 -0.27200033 -0.25348852  0.10235091]
 [-0.50078211  0.06088781 -0.12393263 -0.18320645 -0.00874168  0.39645342
   0.37228392 -0.29590338  0.28025371  0.00268737]]


In [88]:
#4
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 2 8]
 [4 9 9]
 [2 9 2]]
[[3 2 8]
 [4 9 9]
 [2 9 2]]


# Q 7

1. How to tell if a given 2D array has null columns?
2. Find the nearest value from a given value in an array
3. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
4. Create an array class that has a name attribute

In [89]:
#1
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [90]:
#2
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5137943664176939


In [91]:
#3
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [92]:
#4
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# Q 8 
1. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?\
2. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [93]:
#1
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[1. 2. 2. 1. 7. 4. 2. 1. 3. 7.]
[ 1.  3.  3.  1. 13.  7.  3.  1.  5. 13.]


In [94]:
#2
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# Q 9
1. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
2. Considering a four dimensions array, how to get sum over the last two axis at once?

In [95]:
#1
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [96]:
#2
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[53 42 44 64]
 [56 63 80 41]
 [40 51 57 63]]
[[53 42 44 64]
 [56 63 80 41]
 [40 51 57 63]]


# Q 10
1. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
2. How to get the diagonal of a dot product?

In [97]:
#1
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.38602771 0.61773769 0.46027617 0.49242899 0.57085649 0.48825736
 0.39367211 0.62404527 0.47083729 0.50556568]
0    0.386028
1    0.617738
2    0.460276
3    0.492429
4    0.570856
5    0.488257
6    0.393672
7    0.624045
8    0.470837
9    0.505566
dtype: float64


In [98]:
#2
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.43817492, 1.50130073, 1.61525242, 0.86815291, 1.41948983])

# Q 11
1. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
2. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [99]:
#1
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [100]:
#2
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# Q 12
1. How to swap two rows of an array?
2. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles

In [101]:
#1
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [102]:
#2
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 54) ( 0, 62) ( 2, 42) ( 2, 79) ( 3, 40) ( 3, 54) ( 5, 79) ( 5, 90)
 ( 9, 48) ( 9, 54) (16, 26) (16, 97) (18, 54) (18, 85) (26, 97) (28, 36)
 (28, 60) (32, 49) (32, 57) (36, 60) (40, 54) (42, 79) (48, 54) (49, 57)
 (54, 62) (54, 85) (55, 72) (55, 93) (72, 93) (79, 90)]


# Q 13
1. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
2. How to compute averages using a sliding window over an array?

In [103]:
#1
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [104]:
#2
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


# Q 14
1. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
2. How to negate a boolean, or to change the sign of a float inplace?

In [105]:
#1
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [106]:
#2
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.53757771,  0.21888285, -0.42879395, -0.27440061,  0.41873903,
       -0.9457566 , -0.16117223,  0.13060038,  0.15911824,  0.14411907,
        0.83942963, -0.62304794, -0.57397975,  0.66678983,  0.66243769,
        0.29995291,  0.65340762, -0.07462349,  0.99241346,  0.89028769,
        0.28732219, -0.87041831,  0.13908423, -0.24797211,  0.59492445,
        0.1974617 ,  0.2966803 ,  0.02707514,  0.02245023, -0.5751276 ,
       -0.55088692,  0.49385303,  0.89113495, -0.41166066, -0.44602875,
        0.32798316, -0.05453587, -0.40835174, -0.67072596,  0.71149943,
       -0.39420819,  0.03358755, -0.21200804,  0.35637372,  0.22786283,
       -0.65398154,  0.07221833, -0.00257946, -0.16440495,  0.81478916,
        0.03719608, -0.01127811, -0.15584752,  0.35769893, -0.97167265,
       -0.43792232,  0.89027633, -0.45841508, -0.74545098, -0.03843706,
        0.60293969, -0.17768595, -0.04381598,  0.65579857, -0.79189273,
        0.64605381,  0.9816245 ,  0.31479611, -0.49267158,  0.46

# Q 15
1. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
2. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

In [107]:
#1
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.31230472 9.59255201 3.32118795 7.84258202 9.49798014 6.96968036
 1.61731249 2.88070243 3.60477812 4.24652151]


In [108]:
#2
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[9.50134492e+00 6.51756736e+00 5.87333948e+00 1.00834684e+01
  1.53390324e-01 7.56054830e+00 1.40267333e+01 5.54494303e+00
  5.16952667e+00 7.59243828e+00]
 [1.58723219e+00 2.57664557e+00 2.70492512e+00 2.25410200e+00
  5.79346367e+00 4.82216903e+00 6.71280551e+00 5.29392019e-01
  8.51275422e+00 8.46594198e-01]
 [1.29550115e+01 1.10203110e+01 1.01806302e+01 1.31499923e+01
  4.91433911e+00 5.85611203e+00 1.61307756e+01 1.03047128e+01
  8.14393611e-01 1.22867105e+01]
 [1.38387816e+01 1.09304134e+01 9.97748824e+00 1.40909827e+01
  5.16597719e+00 6.71407339e+00 1.71546643e+01 1.05814057e+01
  9.92597133e-01 1.27066706e+01]
 [1.19922669e+01 1.35177423e+01 1.29235703e+01 1.18230014e+01
  6.50758159e+00 2.42153803e+00 1.40775543e+01 1.18216784e+01
  1.87685390e+00 1.33384683e+01]
 [1.44604079e+00 4.85591357e+00 4.73301280e+00 1.55141904e-03
  1.26815087e+01 9.94262822e+00 6.22420397e+00 7.34540389e+00
  1.59571627e+01 5.46381888e+00]
 [5.22889696e-01 5.53033679e+00 5.93984324e+00 7.62827337e

# Q 16
1. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
2. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


In [109]:
#1
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 4 3 9 2 3 3 8 0 3]
 [7 6 0 7 0 8 9 4 7 2]
 [0 4 9 1 6 0 2 5 2 8]
 [9 4 9 3 0 9 4 7 3 4]
 [2 0 6 4 5 7 9 0 9 3]
 [0 8 8 8 1 3 9 1 0 9]
 [7 5 5 0 6 1 6 8 9 1]
 [8 1 2 9 1 7 2 0 3 7]
 [5 4 5 3 8 1 1 7 3 7]
 [5 4 0 7 9 9 7 0 0 4]]
[[0 0 0 0 0]
 [0 3 4 3 9]
 [0 7 6 0 7]
 [0 0 4 9 1]
 [0 9 4 9 3]]


C:\Users\Anudeep\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [110]:
#2
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# Q 17
1. Compute a matrix rank (★★★)
2. How to find the most frequent value in an array?

In [111]:
#1
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [112]:
#2
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


# Q 18
1. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
2. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [113]:
#1
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 1 4]
   [1 4 3]
   [3 2 3]]

  [[1 4 4]
   [4 3 2]
   [2 3 0]]

  [[4 4 3]
   [3 2 4]
   [3 0 2]]

  [[4 3 3]
   [2 4 1]
   [0 2 1]]

  [[3 3 4]
   [4 1 2]
   [2 1 4]]

  [[3 4 3]
   [1 2 4]
   [1 4 1]]

  [[4 3 1]
   [2 4 0]
   [4 1 1]]

  [[3 1 2]
   [4 0 1]
   [1 1 3]]]


 [[[1 4 3]
   [3 2 3]
   [0 3 3]]

  [[4 3 2]
   [2 3 0]
   [3 3 2]]

  [[3 2 4]
   [3 0 2]
   [3 2 4]]

  [[2 4 1]
   [0 2 1]
   [2 4 3]]

  [[4 1 2]
   [2 1 4]
   [4 3 1]]

  [[1 2 4]
   [1 4 1]
   [3 1 4]]

  [[2 4 0]
   [4 1 1]
   [1 4 0]]

  [[4 0 1]
   [1 1 3]
   [4 0 2]]]


 [[[3 2 3]
   [0 3 3]
   [1 2 1]]

  [[2 3 0]
   [3 3 2]
   [2 1 1]]

  [[3 0 2]
   [3 2 4]
   [1 1 1]]

  [[0 2 1]
   [2 4 3]
   [1 1 4]]

  [[2 1 4]
   [4 3 1]
   [1 4 1]]

  [[1 4 1]
   [3 1 4]
   [4 1 3]]

  [[4 1 1]
   [1 4 0]
   [1 3 3]]

  [[1 1 3]
   [4 0 2]
   [3 3 0]]]


 [[[0 3 3]
   [1 2 1]
   [2 3 0]]

  [[3 3 2]
   [2 1 1]
   [3 0 3]]

  [[3 2 4]
   [1 1 1]
   [0 3 4]]

  [[2 4 3]
   [1 1 4]
   [3 4 1]]

  [[4 3 1]
   

In [114]:
#2
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 14  1 11  4]
 [14  9  8  6 13]
 [ 1  8  0 42  8]
 [11  6 42  2 13]
 [ 4 13  8 13  0]]


# Q 19
1. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
2. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [115]:
#1
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [116]:
#2
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


# Q 20
1. How to implement the Game of Life using numpy arrays?
2. How to get the n largest values of an array

In [117]:
#1
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [118]:
#2
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


# SECTION C

This section is scenario based. Each question carries 15 marks

# Q 1
Using python, develop a phone directory

Hint:

###### def print_menu():
######    print('1. Print Phone Numbers')
######    print('2. Add a Phone Number')
######    print('3. Remove a Phone Number')
######    print('4. Lookup a Phone Number')
######    print('5. Quit')

In [ ]:
def print_menu():
    print('1. Print Phone Numbers')
    print('2. Add a Phone Number')
    print('3. Remove a Phone Number')
    print('4. Lookup a Phone Number')
    print('5. Quit')
    print()

numbers = {}
menu_choice = 0
print_menu()
while menu_choice != 5:
    menu_choice = int(input("Type in a number (1-5): "))
    if menu_choice == 1:
        print("Telephone Numbers:")
        for x in numbers.keys():
            print("Name: ", x, "\tNumber:", numbers[x])
        print()
    elif menu_choice == 2:
        print("Add Name and Number")
        name = input("Name: ")
        phone = input("Number: ")
        numbers[name] = phone
    elif menu_choice == 3:
        print("Remove Name and Number")
        name = input("Name: ")
        if name in numbers:
            del numbers[name]
        else:
            print(name, "was not found")
    elif menu_choice == 4:
        print("Lookup Number")
        name = input("Name: ")
        if name in numbers:
            print("The number is", numbers[name])
        else:
            print(name, "was not found")
    elif menu_choice != 5:
        print_menu()

# Q 2
Using python, develop a database of students with their grades

###### def print_menu():
######    print("1. Add student")
######    print("2. Remove student")
######    print("3. Print grades")
######    print("4. Record grade")
######    print("5. Print Menu")
######    print("6. Exit")

In [ ]:
max_points = [25, 25, 50, 25, 100]
assignments = ['hw ch 1', 'hw ch 2', 'quiz   ', 'hw ch 3', 'test']
students = {'#Max': max_points}

def print_menu():
    print("1. Add student")
    print("2. Remove student")
    print("3. Print grades")
    print("4. Record grade")
    print("5. Print Menu")
    print("6. Exit")

def print_all_grades():
    print('\t', end=' ')
    for i in range(len(assignments)):
        print(assignments[i], '\t', end=' ')
    print()
    keys = list(students.keys())
    keys.sort()
    for x in keys:
        print(x, '\t', end=' ')
        grades = students[x]
        print_grades(grades)

def print_grades(grades):
    for i in range(len(grades)):
        print(grades[i], '\t', end=' ')
    print()

print_menu()
menu_choice = 0
while menu_choice != 6:
    print()
    menu_choice = int(input("Menu Choice (1-6): "))
    if menu_choice == 1:
        name = input("Student to add: ")
        students[name] = [0] * len(max_points)
    elif menu_choice == 2:
        name = input("Student to remove: ")
        if name in students:
            del students[name]
        else:
            print("Student:", name, "not found")
    elif menu_choice == 3:
        print_all_grades()
    elif menu_choice == 4:
        print("Record Grade")
        name = input("Student: ")
        if name in students:
            grades = students[name]
            print("Type in the number of the grade to record")
            print("Type a 0 (zero) to exit")
            for i in range(len(assignments)):
                print(i + 1, assignments[i], '\t', end=' ')
            print()
            print_grades(grades)
            which = 1234
            while which != -1:
                which = int(input("Change which Grade: "))
                which -= 1    #same as which = which - 1
                if 0 <= which < len(grades):
                    grade = int(input("Grade: "))
                    grades[which] = grade
                elif which != -1:
                    print("Invalid Grade Number")
        else:
            print("Student not found")
    elif menu_choice != 6:
        print_menu()